# Generated by Django 3.1.5 on 2021-01-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_profile',
            field=models.ImageField(default='default.jpg', upload_to='group_profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(default='This is about', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_profile',
            field=models.ImageField(default='default.jpg', upload_to='user_profile'),
        ),
    ]
